server:
  port: 5002

spring:
  application:
    name: salon-service

  datasource:
    url: jdbc:mysql://localhost:3306/salon_management
    username: root
    password: tejastc
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true