server:
  port: 5004

spring:
  application:
    name: service-offering

  datasource:
    url: jdbc:mysql://localhost:3306/salon_services
    username: root
    password: tejastc
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true